config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :users
  resources :posts do
    collection do
      get "my_drafts"
    end
    member do
      get "approve_or_reject"
    end
  end

  get "sign_up", to: "registration#new"
  post "sign_up", to: "registration#create"

  get "log_in", to: "sessions#new"
  post "log_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :attachments

  STATUS_DRAFT = "черновик"
  STATUS_INSPECT = "на проверке"
  STATUS_APPROVED = "утвержден"
  STATUS_REJECTED = "отклонен"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :delete_all

  include ActiveModel::SecurePassword
  has_secure_password

  validates :login, presence: true, uniqueness: true
  validates_presence_of :region, if: proc {|u| !u.admin?}

  validates_presence_of :firstname, if: proc {|u| !u.admin?}
  validates_presence_of :lastname, if: proc {|u| !u.admin?}
  validates_presence_of :prename, if: proc {|u| !u.admin?}



  validates :password, presence: true
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authorized
  helper_method :current_user
  helper_method :logged_in?
  def current_user
    User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
  # def authorized
  #   redirect_to log_in_path unless logged_in?
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorized

  def index
    if current_user.admin?
      @posts = Post.where(status: Post::STATUS_INSPECT)
    else
      @posts = Post.where(status: Post::STATUS_APPROVED, region: current_user.region)
    end
    authors_ids = @posts.pluck(:user_id).uniq
    @authors = User.where(id: authors_ids)
    scope = params[:user_id].blank? ? @posts.all : @posts.where(user_id: params[:user_id])
    scope = scope.where("LOWER(region) LIKE LOWER(?)", "%#{params[:region].downcase}%") if params[:region].present?
    if params[:created_at_from].present?
      created_at_from_date = Date.parse(params[:created_at_from])
      scope = scope.select{|x| x.created_at.to_date >= created_at_from_date}
    end

    if params[:created_at_to].present?
      created_at_to_date = Date.parse(params[:created_at_to])
      scope = scope.select{|x| x.created_at.to_date <= created_at_to_date}
    end

    @posts = @posts.where(id: scope.pluck(:id))

    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def my_drafts
    @posts = Post.where(user_id: current_user.id, status: [Post::STATUS_DRAFT, Post::STATUS_INSPECT, Post::STATUS_REJECTED])
  end

  def new
    @post = Post.new()
  end

  def create
    byebug
    @post = Post.create(post_params)
    status = if params[:to_draft].present?
                     Post::STATUS_DRAFT
                   elsif params[:to_inspect].present?
                     Post::STATUS_INSPECT
                   elsif params[:to_approved].present?
                     Post::STATUS_APPROVED
                   end
    @post.update(user_id: current_user.id, region: current_user.region, status: status)

    if @post.save
      redirect_to posts_path, notice: "Successfully created post!"

    else
      render :new
    end
  end

  def approve_or_reject
    post = Post.find(params[:id])
    status = case params[:status]
    when "approve"
      Post::STATUS_APPROVED
    when "reject"
      Post::STATUS_REJECTED
    else
      Post::STATUS_INSPECT
    end
    post.update(status: status, created_at: DateTime.now)
    redirect_to posts_path
  end


  def authorized
    redirect_to log_in_path unless logged_in?
  end

  private
  def post_params
    params.require(:post).permit(:text, attachments:[])
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id

      redirect_to posts_path, notice: "Successfully created account!"

    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation, :firstname, :lastname, :prename, :region)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(login: params[:login])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path, notice: "Successfully logged in"
    else
      redirect_to log_in_path, alert: 'Invalid email or password'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to log_in_path, notice: 'Logged out successfully.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if params[:admin] == "true"
      @user = User.new
    end
  end

  def create
    @user = User.new(admin: true)
    @user.update(user_params)

    if @user.save
      redirect_to posts_path, notice: "Successfully created admin!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation, :firstname, :lastname, :prename, :region)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="header">
  <span style="margin: 0 10px;">
    <%= link_to "Создать пост", new_post_path, class: "blue" %>
  </span>
  <span style="margin: 0 10px;">
    <%= link_to "Посты", posts_path, class: "blue" %>
  </span>
  <% if current_user && !current_user.admin? %>
    <span style="margin: 0 10px;">
      <%= link_to "Мои черновики", my_drafts_posts_path, class: "blue" %>
    </span>
  <% end %>


  <% if current_user && current_user.admin? %>
    <span style="margin-right: 20px;">
      <%= link_to "Создать админа", new_user_path(admin: true), class: "blue" %>
    </span>
  <% end %>

  <% if !current_user.present? %>
    <span style="float: right; margin-right: 20px;">
      <%= link_to "Зарегистрироваться", sign_up_path, class: "white" %>
    </span>
  <% end %>
  <span style="float: right; margin-right: 20px;">
    <% if current_user.present? %>
      <span style="margin: 0 15px;"><%= current_user.login %></span>
      <%= link_to "Выйти", logout_path, method: :delete, class: "white" %>
    <% else %>
      <%= link_to "Войти", log_in_path, class: "white" %>
    <% end %>
  </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ano</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_posts.html.erb
<div style="margin: 30px;">
  <% if !@posts.nil? %>
    <% @posts.each do |post| %>
      <div>
        <%= "#{post.user.login} (#{post.region}) #{post.created_at.strftime("%d.%m.%Y")}:" %>
      </div>
      <div style="border: 1px solid grey; width: 300px; border-radius: 4px;  padding: 10px 5px;">
        <%= post.text %>
      </div>
      <% if post.attachments.present? %>
        <div style="border: 1px solid grey; width: 300px; border-radius: 4px;  padding: 10px 5px;">
          <% post.attachments.each do |atta| %>
            <%= link_to atta do %>
              <% if atta.content_type.include?("image") %>
                <%= image_tag(atta, style: "width: 30px") %>
              <% else %>
                <%= image_tag("document.png", style: "width: 30px") %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <% if params[:action] == "my_drafts" %>
        <div>
          <%= post.status %>
        </div>
      <% end %>
      <div style="margin: 0 10px 20px 0; font-size: 12px">
        <% if current_user.admin? %>
          <%= link_to "Утвердить", approve_or_reject_post_path(post.id, status: :approve), style: "color: green" %>
          <%= link_to "Отклонить", approve_or_reject_post_path(post.id, status: :reject), style: "color: red" %>
        <% else %>
          <% if post.status == Post::STATUS_DRAFT %>
            <%= link_to "Удалить", post_path(post.id), method: :delete, style: "color: red" if current_user.id == post.user_id %>
            <%= link_to "На проверку", approve_or_reject_post_path(post.id, status: :inspect), style: "color: orange" %>
          <% end %>
        <% end %>
      </div>

<% end %>
  <% else %>
    <%= "В вашем регионе пока нет постов, создайте первый" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= form_tag(posts_path, { :method => :get }) do %>
  <fieldset>
    <legend><%= "Поиск" %></legend>

    <label for='region'><%= "Регион" %>:</label>
    <%= text_field_tag 'region', params[:region] %>

    <% if !@authors.nil? %>
      <label for='user_id'><%= "Автор поста" %>:</label>
      <%= select_tag 'user_id', content_tag('option') + options_from_collection_for_select(@authors, :id, :login, params[:user_id].to_i), :onchange => "this.form.submit(); return false;"  %>
    <% end %>

    <label for='created_at_from'><%= "Дата создания (от)" %>:</label>
    <%= date_field_tag 'created_at_from', params[:created_at_from] %>

    <label for='created_at_to'><%= "Дата создания (по)" %>:</label>
    <%= date_field_tag 'created_at_to', params[:created_at_to] %>

    <%= submit_tag "Поиск", class: "new_reg_btn" %>
    <%= link_to "Очистить", posts_path %>
  </fieldset>
<% end %>

<%= render "posts" %>

<%= link_to "Экспорт в XLSX", posts_path(format: "xlsx"), class: "blue" %>

app/views/posts/my_drafts.html.erb
<%= render "posts" %>

app/views/posts/new.html.erb
<div class="main_reg_block">
  <h1 class="new_btn_block"> Новый пост </h1>
  <hr>

  <%= form_for @post, url: posts_url, html: { method: :post } do |form| %>


    <% if @post.errors.any? %>
      <div class="alert alert-danger">
        <% @post.errors.full_messages.each do |message|%>
          <div>
            <%= message %> <% end %>
        </div>
      </div>
    <% end %>
    <div class="new_input">
      <%= form.label :text, "Текст" %>
      <%= form.text_area :text, class: "form-control", placeholder: "Напишите, что думаете", rows: 7 %>
    </div>

    <%= form.file_field :attachments, multiple: true %>

    <hr>


    <% if current_user.admin? %>
      <div class="new_btn_block">
        <%= form.submit "Сохранить черновик", name: 'to_approved', class: 'btn btn-primary new_reg_btn' %>
      </div>
    <% else %>
      <div class="new_btn_block">
        <%= form.submit "Сохранить черновик", name: "to_draft", class: 'btn btn-primary new_reg_btn' %>
      </div>

      <div class="new_btn_block">
        <%= form.submit "Отправить на проверку", name: "to_inspect", class: 'btn btn-primary new_reg_btn' %>
      </div>
    <% end %>

<% end %>
</div>

app/views/users/new.html.erb
<div class="main_reg_block">
  <h1 class="new_btn_block"> Создать админа </h1>
  <hr>

  <%= form_for @user, url: users_url, html: { method: :post } do |form| %>

    <% if @user.errors.any? %>
      <div class="alert alert-danger">
        <% @user.errors.full_messages.each do |message|%>
          <div>
            <%= message %> <% end %>
        </div>
      </div>
    <% end %>
    <div class="new_input">
      <%= form.label :login, "Логин" %>
      <%= form.text_field :login, class: "form-control", placeholder: "myname" %>
    </div>
    <div class="new_input">
      <%= form.label :password, "Пароль" %>
      <%= form.password_field :password,  class: "form-control", placeholder: "********"%>
    </div>
    <div class="new_input">
      <%= form.label :password_confirmation, "Подтверждение пароля" %>
      <%= form.password_field :password_confirmation,  class: "form-control", placeholder: "********"%>
    </div>


    <div class="new_input">
      <%= form.label :lastname, "Фамилия" %>
      <%= form.text_field :lastname,  class: "form-control", placeholder: "Иванов"%>
    </div>
    <div class="new_input">
      <%= form.label :firstname, "Имя" %>
      <%= form.text_field :firstname,  class: "form-control", placeholder: "Иван"%>
    </div>
    <div class="new_input">
      <%= form.label :prename, "Отчество" %>
      <%= form.text_field :prename,  class: "form-control", placeholder: "Иванович"%>
    </div>
    <div class="new_input">
      <%= form.label :region, "Регион" %>
      <%= form.text_field :region,  class: "form-control", placeholder: "Астраханская область"%>
    </div>

    <hr>

    <div class="new_btn_block">
      <%= form.submit "Создать", class: 'btn btn-primary new_reg_btn' %>
    </div>
  <% end %>
</div>